In [1]:
import numpy as np

In [2]:
''' Some vectors '''
v1 = np.array([1,4])
v2 = np.array([3,-1])

In [7]:
''' 
    Linear Maps (Matrix) 
    2D arrays -> arrays of arrays
    row major language
    
    Row major notation (this is the default in python)
    np.array([[2,6],[7,5]])
    -> 
    ( 2 6 )
    ( 7 5 )
    
    Column major notation (Fortran)
    np.array([[2,6],[7,5]])
    -> 
    ( 2 7 )
    ( 6 5 )
    
'''

''' f : R^2 -> R^2 '''
f = np.array([[2,6],[7,5]])
print(f)

[[2 6]
 [7 5]]


In [8]:
''' Swap between notations '''
f_cm = f.T
print(f_cm)

[[2 7]
 [6 5]]


In [10]:
''' f (v1) 
    
    Mat(f) . v1 
    -> 
    f @ v1

'''

f_v1 = f @ v1
print(f_v1)

[26 27]


In [12]:
''' Another linear map '''

'''
    Mat(f)
    -> 
    ( 2 7 )
    ( 6 5 )
    f : R^2 -> R^2 


    Mat(g) = 
    ->
    (3  5 )
    (7  0 )
    (-1 2 )
    g : R^2 -> R^3
    
    f o g ? No
    
    g o f ? Yes
    g o f : R^2 -> R^3
    
    f o f ? Yes 
    f o f : R^2 -> R^2
    
    g o g ? No

''' 
g = np.array([[3,5],[7,0],[-1,2]])

In [13]:
g_after_f = g @ f

In [17]:
''' Ask python to tell you the shape of the matrix '''
g_after_f.shape

(3, 2)

In [19]:
''' Addition: 
    they must have the same source and target 
    they have the same shape
'''

print(g)
print(g_after_f)
print(g + g_after_f)


[[ 3  5]
 [ 7  0]
 [-1  2]]
[[41 43]
 [14 42]
 [12  4]]
[[44 48]
 [21 42]
 [11  6]]


In [20]:
print(3*f)

[[ 6 18]
 [21 15]]


In [ ]:
''' 
    L(R^2,R^5) ~ R^10 
    
    dim(L(U,V)) = dim(U) * dim(V)

'''
