In [1]:
import numpy as np

In [2]:
v1 = np.array([1,4,-7])
v2 = np.array([0,-3,-1])
v3 = np.array([5,0,1])

In [3]:
""" We want a function that takes the three vectors v1,v2,v3 and returns an orthogonal set """

def orthogonalize(w1,w2,w3): # ":" marks the beginning of a scope
    w1p = w1
    
    """ 
        Subtract from v2 the piece that is parallel to v1p 
        
        v1 . v2  ----> v1 @ v2
    
    """
    w2p = w2 - ((w2 @ w1p)/(w1p @ w1p))*w1p
    
    w3p = w3 - ((w3 @ w1p)/(w1p @ w1p))*w1p - ((w3 @ w2p)/(w2p @ w2p))*w2p
    
    return w1p,w2p,w3p

In [4]:
z1p,z2p,z3p = orthogonalize(v1,v2,v3)

In [5]:
z1p,z2p,z3p

(array([ 1,  4, -7]),
 array([ 0.07575758, -2.6969697 , -1.53030303]),
 array([ 5.03937008, -0.2015748 ,  0.60472441]))

In [8]:
print("z1p . z2p =",z1p @ z2p)
print("z2p . z3p =",z2p @ z3p)
print("z3p . z1p =",z3p @ z1p)

z1p . z2p = 0.0
z2p . z3p = 1.1102230246251565e-16
z3p . z1p = 0.0


In [ ]:
0.00000000000000011102

In [10]:
print("v1 . v2 =",v1@v2)
print("v2 . v3 =",v2@v3)
print("v3 . v1 =",v3@v1)

v1 . v2 = -5
v2 . v3 = -1
v3 . v1 = -2


In [15]:
w1p,w2p,w3p = orthogonalize(v1,v2,3*v1-7*v2+np.array([0.5,0.5,0.5]))

In [16]:
w3p

array([ 0.53149606, -0.02125984,  0.06377953])

In [14]:
w2p

array([ 0.07575758, -2.6969697 , -1.53030303])